openapi: 3.0.0
info:
  description: "STN-Node is service that crates shorter links and captures clicks."
  version: "v0.1-dev"
  title: "STN-Node API"
servers:
  - url: ""
tags:
- name: "Profile"
  description: ""
- name: "Petition"
  description: ""
- name: "Donation"
  description: ""
- name: "STN-Node API"
  description: ""
paths:
  /people/george-floyd:
    post:
      tags:
      - "Profile"
      summary: "Request shorter url for profile -mobile"
      parameters:
      - name: "meta-client"
        in: "header"
        schema:
          type: "string"
        description: ""
        required: true
      - name: "meta-url"
        in: "header"
        schema:
          type: "string"
        description: ""
        required: true
      responses:
        200:
          description: "successful operation"
  /petition/ban-use-of-inhumane-rubber-bullets:
    post:
      tags:
      - "Petition"
      summary: "Request shorter url for petition -mobile"
      parameters:
      - name: "meta-client"
        in: "header"
        schema:
          type: "string"
        description: ""
        required: true
      - name: "meta-url"
        in: "header"
        schema:
          type: "string"
        description: ""
        required: true
      responses:
        200:
          description: "successful operation"
  /donation/black-lives-matter-fund:
    post:
      tags:
      - "Donation"
      summary: "Request shorter url for donation -mobile"
      parameters:
      - name: "meta-client"
        in: "header"
        schema:
          type: "string"
        description: ""
        required: true
      - name: "meta-url"
        in: "header"
        schema:
          type: "string"
        description: ""
        required: true
      responses:
        200:
          description: "successful operation"
  /p=fbeHQhN3:
    get:
      tags:
      - "STN-Node API"
      summary: "Passing shorten url and recievening original value - mobile"
      parameters:
      - name: "meta-client"
        in: "header"
        schema:
          type: "string"
        description: ""
        required: true
      responses:
        200:
          description: "successful operation"