name: Generate Docs

on:
  pull_request:
    branches: [master]

jobs:
  serve-api-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      - name: Install Dependencies
        run: npm install --save
      - name: Build API docs
        run: |
          swagger-jsdoc -d ./server/api/routes/*.js -o ./docs/swagger.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update api docs
